### ISSUE TITLE
Crashes on run with a traceback indicating $HOME doesn't exist (OBS 2.7)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-tar_scm#122]
On my private OBS instances, I've been attempting to use the tar_scm source service, only for it to fail with the following error: `Files could not be expanded: KeyError: 'HOME'`.

A little bit of digging led to the following recorded traceback:

```

service tar_scm failed:
Traceback (most recent call last):
  File "/usr/lib/obs/service//tar_scm", line 19, in <module>
    import TarSCM
  File "/usr/lib/obs/service/TarSCM/__init__.py", line 4, in <module>
    from TarSCM.tasks      import tasks
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 10, in <module>
    import TarSCM.scm
  File "/usr/lib/obs/service/TarSCM/scm/__init__.py", line 1, in <module>
    from TarSCM.scm.git import git
  File "/usr/lib/obs/service/TarSCM/scm/git.py", line 5, in <module>
    from TarSCM.scm.base import scm
  File "/usr/lib/obs/service/TarSCM/scm/base.py", line 16, in <module>
    from TarSCM.changes import changes
  File "/usr/lib/obs/service/TarSCM/changes.py", line 11, in <module>
    from TarSCM.config import config
  File "/usr/lib/obs/service/TarSCM/config.py", line 20, in <module>
    class config():
  File "/usr/lib/obs/service/TarSCM/config.py", line 25, in config
    os.path.join(os.environ['HOME'],'.obs','tar_scm')
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'HOME'

```

On my OBS appliances, I have the following version of the service:

```
build:~ # rpm -qa | grep tar_scm
obs-service-tar_scm-0.7.0.1477567374.d44d677-138.1.noarch
```

**Comment by Conan-Kudo** [comment]
Upgrading to the latest version (`obs-service-tar_scm-0.7.0.1477858520.51a62fb-139.1.noarch`) does not fix it:

```

service tar_scm failed:
Traceback (most recent call last):
  File "/usr/lib/obs/service//tar_scm", line 19, in <module>
    import TarSCM
  File "/usr/lib/obs/service/TarSCM/__init__.py", line 4, in <module>
    from TarSCM.tasks      import tasks
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 10, in <module>
    import TarSCM.scm
  File "/usr/lib/obs/service/TarSCM/scm/__init__.py", line 1, in <module>
    from TarSCM.scm.git import git
  File "/usr/lib/obs/service/TarSCM/scm/git.py", line 5, in <module>
    from TarSCM.scm.base import scm
  File "/usr/lib/obs/service/TarSCM/scm/base.py", line 17, in <module>
    from TarSCM.changes import changes
  File "/usr/lib/obs/service/TarSCM/changes.py", line 11, in <module>
    from TarSCM.config import config
  File "/usr/lib/obs/service/TarSCM/config.py", line 20, in <module>
    class config():
  File "/usr/lib/obs/service/TarSCM/config.py", line 25, in config
    os.path.join(os.environ['HOME'],'.obs','tar_scm')
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'HOME'

```

**Comment by M0ses** [comment]
Thats weird - $HOME should be set in any environment could you check your environment, e.g. "$HOME" - A workaround could be provided quickly but I`m wondering were this is coming from.

**Comment by Conan-Kudo** [comment]
@M0ses Well, my OBS appliances are stock appliances installed from the ISO, just with updates applied. Whatever they have is what I have.

At least when I log in as root, I do have $HOME, but I don't know what user the OBS services run as.

**Comment by M0ses** [comment]
I bet, it is not set. Could you post the output of "grep 'obsservicerun:' /etc/passwd" ?

**Comment by Conan-Kudo** [comment]
```
build:~ # grep 'obsservicerun:' /etc/passwd
obsservicerun:x:498:496:User for the build service source service:/usr/lib/obs:/sbin/nologin
build:~ #
```

**Comment by M0ses** [comment]
Hmm, looks good to me. Anyway, I wrote a fix:

https://github.com/M0ses/obs-service-tar_scm/commit/e162c6680747b137966ab694f7d37d33f0f5f72b

which is building ATM:

https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-tar_scm

so wait for obs-service-tar_scm-0.7.0.1478249268.e162c66 and be aware, that you need openSUSE:Tools in your repo list

**Comment by M0ses** [comment]
Please let me know if the fix worked for you.

**Comment by Conan-Kudo** [comment]
@M0ses My issue is fixed now. Thanks!
