### ISSUE TITLE
AttributeError final_rename_needed when running at buildtime

### ISSUE THREAD

**Issue by M0ses** [openSUSE/obs-service-tar_scm#173]
```
[   27s] Running build time source services...
[   27s] Traceback (most recent call last):
[   27s]   File "/usr/lib/obs/service/tar", line 30, in <module>
[   27s]     main()
[   27s]   File "/usr/lib/obs/service/tar", line 26, in main
[   27s]     TarSCM.run()
[   27s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 35, in run
[   27s]     task_list.process_list()
[   27s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 109, in process_list
[   27s]     self.process_single_task(task)
[   27s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 213, in process_single_task
[   27s]     scm_object.finalize()
[   27s]   File "/usr/lib/obs/service/TarSCM/scm/tar.py", line 58, in finalize
[   27s]     if self.final_rename_needed:
[   27s] AttributeError: Tar instance has no attribute 'final_rename_needed'
[   27s] service run failed for service 'tar'
[   27s] 
```

**Comment by M0ses** [comment]
fixed in PR #174
