### ISSUE TITLE
Use of uninitialized value $val in concatenation (.) or string at /usr/lib/obs/server/bs_admin line 1144.

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/obs-service-tar_scm#186]
I tried re-triggering a few times. Now it shows an error message instead of an endless "in progress":

```
service tar_scm failed: 
Use of uninitialized value $val in concatenation (.) or string at /usr/lib/obs/server/bs_admin line 1144. 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/bs/service/15856 
/bs/service/15856/src 
/bs/service/15856/src/_service 
/bs/service/15856/src/openra.changes 
/bs/service/15856/src/openra.spec 
/bs/service/15856/src/thirdparty.tar.gz 
/bs/service/15856/src/.old 
/bs/service/15856/out 
/bs/service/15856/var 
/bs/service/15856/var/cache 
/bs/service/15856/var/cache/obs 
/bs/service/15856/var/cache/obs/xQV5mSWhr6fX 
/bs/service/15856/var/cache/obs/xQV5mSWhr6fX/scripts 
/bs/service/15856/var/cache/obs/xQV5mSWhr6fX/scripts/inner.sh 
/bs/service/15856/var/cache/obs/xQV5mSWhr6fX/scripts/inner.sh.command 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes 
runtime/cgo: pthread_create failed: Resource temporarily unavailable 
SIGABRT: abort 
PC=0x7fbcc55f98d7 m=0

goroutine 0 [idle]:

goroutine 1 [running, locked to thread]: 
runtime.systemstack_switch() 
/usr/lib64/go/src/runtime/asm_amd64.s:245 fp=0xc820043e90 sp=0xc820043e88 
runtime.newproc(0x0, 0xe2e5c8) 
/usr/lib64/go/src/runtime/proc.go:2659 +0x62 fp=0xc820043ed8 sp=0xc820043e90 
runtime.init.4() 
/usr/lib64/go/src/runtime/proc.go:218 +0x2b fp=0xc820043ef0 sp=0xc820043ed8 
runtime.init() 
/usr/lib64/go/src/runtime/write_err.go:13 +0x378 fp=0xc820043f50 sp=0xc820043ef0 
runtime.main() 
/usr/lib64/go/src/runtime/proc.go:140 +0x103 fp=0xc820043fa0 sp=0xc820043f50 
runtime.goexit() 
/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820043fa8 sp=0xc820043fa0

goroutine 17 [syscall, locked to thread]: 
runtime.goexit() 
/usr/lib64/go/src/runtime/asm_amd64.s:1998 +0x1

rax 0x0 
rbx 0x7fbcc59636b8 
rcx 0x7fbcc55f98d7 
rdx 0x6 
rdi 0x3e18 
rsi 0x3e18 
rbp 0xe5e6be 
rsp 0x7ffde2eaad68 
r8 0xa 
r9 0x7fbcc5d94740 
r10 0x8 
r11 0x206 
r12 0x17f4050 
r13 0xe2b61c 
r14 0x0 
r15 0x8 
rip 0x7fbcc55f98d7 
rflags 0x206 
cs 0x33 
fs 0x0 
gs 0x0 
/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes
```

https://build.opensuse.org/package/show/games:openra/playtest

**Comment by aspiers** [comment]
@M0ses Any ideas?  To me this looks more like something ran out of system resources, rather than it being an issue with `tar_scm`.

**Comment by Mailaender** [comment]
Yes, the repository is rather large. I had to switch to a static tarball now due to this error and I couldn't switch to the new cached repos due to https://github.com/openSUSE/obs-service-tar_scm/issues/185.

**Comment by aspiers** [comment]
I think there are two issues here though:

- `Use of uninitialized value $val in concatenation (.) or string`, which *might* be related to  https://github.com/openSUSE/open-build-service/issues/3096
- `fork: retry: No child processes` due to running out of resources

However I don't see how either of them are related to `tar_scm`.  Am I missing something?

**Comment by Mailaender** [comment]
The error message said

> service tar_scm failed

so I thought this was the right place.

**Comment by aspiers** [comment]
Sure - I'm not criticising your assumption, but I'm fairly sure that `/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes` show that the system ran out of resources in the container even before `tar_scm` was triggered.  Hopefully @M0ses or @adrianschroeter can shed more light here.

**Comment by M0ses** [comment]
I`m quite sure that this is not a problem of tar_scm, so I'm closing this issue.

```/usr/lib/obs/server/call-service-in-docker.sh: fork: retry: No child processes```

indicates that there are no resources to create a new container.

Please try again and report if the problem still persists
