### ISSUE TITLE
UnicodeDecodeError in changes.py

### ISSUE THREAD

**Issue by vadorovsky** [openSUSE/obs-service-tar_scm#264]
After updating obs-service-tar_scm today, to the 0.9.5.1542905297.a6e346a-224.1 version, I'm getting the following error:

```
 mrostecki  ~  obs  home:mrostecki  jwt-verify  osc service disabledrun
Cloning into '/home/mrostecki/obs/home:mrostecki/jwt-verify/jwt_verify_lib'...
a1298efde49c8f2329e8c124a2389c37845cacf5
Traceback (most recent call last):
  File "/usr/lib/obs/service/tar_scm", line 30, in <module>
    main()
  File "/usr/lib/obs/service/tar_scm", line 26, in main
    TarSCM.run()
  File "/usr/lib/obs/service/TarSCM/__init__.py", line 35, in run
    task_list.process_list()
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 116, in process_list
    self.process_single_task(task)
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 226, in process_single_task
    detected_changes)
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 244, in _process_changes
    changesversion, changesauthor)
  File "/usr/lib/obs/service/TarSCM/changes.py", line 199, in write_changes
    tmp_fp.write(str(old_fp.read()).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 104: ordinal not in range(128)
Aborting: service call failed:  /usr/lib/obs/service/tar_scm --url https://github.com/google/jwt_verify_lib --scm git --changesgenerate enable --filename jwt-verify --versionformat %cd --outdir /home/mrostecki/obs/home:mrostecki/jwt-verify/tmpOdYIze.tar_scm.service
```

The package which I wanted to update by the tar_scm service is:

https://build.opensuse.org/package/show/home:mrostecki/jwt-verify

Which is based on the following git repo:

https://github.com/google/jwt_verify_lib

**Comment by mrostecki** [comment]
I debugged that by pdb and it seems that the problem is about misusing `encode` - `decode` should be used instead.

```
 mrostecki  ~  obs  home:mrostecki  jwt-verify  1  osc service disabledrun
Detected cached repository...
a1298efde49c8f2329e8c124a2389c37845cacf5
> /usr/lib/obs/service/TarSCM/changes.py(200)write_changes()
-> tmp_fp.write(str(old_fp.read()).encode('utf-8'))
(Pdb) content = old_fp.read()
(Pdb) pp content
'-------------------------------------------------------------------\nSun Nov 18 18:51:00 UTC 2018 - Micha\xc5\x82 Rostecki <mrostecki@suse.de>\n\n- Initial release - 20180816\n'
(Pdb) pp str(content)
'-------------------------------------------------------------------\nSun Nov 18 18:51:00 UTC 2018 - Micha\xc5\x82 Rostecki <mrostecki@suse.de>\n\n- Initial release - 20180816\n'
(Pdb) str(content).encode('utf-8')
*** UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 104: ordinal not in range(128)
(Pdb) str(content).decode('utf-8')
u'-------------------------------------------------------------------\nSun Nov 18 18:51:00 UTC 2018 - Micha\u0142 Rostecki <mrostecki@suse.de>\n\n- Initial release - 20180816\n'
```

**Comment by mrostecki** [comment]
Oh, pardon. Actually, I think that both `encode` or `decode` should not be used.

The only purpose of this line:

https://github.com/openSUSE/obs-service-tar_scm/blob/master/TarSCM/changes.py#L199

is copying the file content between descriptors. I don't think we should even care about encoding here. Am I wrong? Is there anything in Python 3 which brings the necessity of encoding the result of `read()` method?

The following diff fixed the issue locally:

```
199c199
<         tmp_fp.write(str(old_fp.read()).encode('utf-8'))
---
>         tmp_fp.write(old_fp.read())
```

**Comment by mrostecki** [comment]
I checked whether reading/writing UTF-8 files without encoding/decoding works on Python 3. Everything seems fine:

```
 mrostecki  ~  cat foo
łąężńżø
 mrostecki  ~  python3
Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> old_fp = open('foo', 'r')
>>> new_fp = open('bar', 'w+')
>>> new_fp.write(old_fp.read())
8
>>> 
 mrostecki  ~  cat bar
łąężńżø
```

**Comment by darix** [comment]
same here

**Comment by foursixnine** [comment]
\o/ same here for https://build.opensuse.org/package/live_build_log/devel:openQA/openQA/openSUSE_Tumbleweed/x86_64

**Comment by doccaz** [comment]
This is causing problems packaging lib3270 from the pw3270 repository as well: https://build.opensuse.org/package/show/home:PerryWerneck:pw3270/lib3270-unstable

tar_scm will fail with the same message due to a changelog entry with accented characters(!)

**Comment by LebedevRI** [comment]
+1
https://build.opensuse.org/package/live_build_log/graphics:darktable:master/darktable/openSUSE_Tumbleweed_ARM/aarch64
