### ISSUE TITLE
using git credentials (server side) not possible

### ISSUE THREAD

**Issue by dsamx** [openSUSE/obs-service-tar_scm#286]
It is currently not possible to use server side git credentials. This is required for the scenario where the git server requires a login and OBS should be able to clone repos without the need to include any credentials in the URL of the _service file.

It does not work because the service currently has no $HOME which means git will never find the git global configuration $HOME/.gitconfig and $HOME/.git-credentials.

If I add def _get_scm_cmd(self):
        os.environ["HOME"] = "/usr/lib/obs"
to git.py it works but the problem is that services don't have homes and /usr/lib/obs actually belongs to root (which is a permission problem for locking the credentials file if it resides in this directory) but is the home of all OBS-users, so the global git/credential configuration should be placed somewhere else.

Please allow a server side configuration for git credentials.

**Comment by dsamx** [comment]
Example service file to reproduce the error:
```
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">http://user@host/repo.git</param>
    <param name="revision">develop</param>
    <param name="filename">testpackage</param>
    <param name="version">1.0</param>
  </service>

  <service name="extract_file">
    <param name="archive">*.tar</param>
    <param name="files">*/*.spec</param>
  </service>
```

Error output:
```
service tar_scm failed:
ERROR(128): "Cloning into '/srv/obs/service/11565/out/tmpLgoRio/testpackage'...
fatal: could not read Password for 'http://.....': No such device or address
"
Traceback (most recent call last):
File "/usr/lib/obs/service//tar_scm", line 30, in
main()
File "/usr/lib/obs/service//tar_scm", line 26, in main
TarSCM.run()
File "/usr/lib/obs/service/TarSCM/__init__.py", line 35, in run
task_list.process_list()
File "/usr/lib/obs/service/TarSCM/tasks.py", line 116, in process_list
self.process_single_task(task)
File "/usr/lib/obs/service/TarSCM/tasks.py", line 184, in process_single_task
scm_object.fetch_upstream()
File "/usr/lib/obs/service/TarSCM/scm/base.py", line 90, in fetch_upstream
self.fetch_upstream_scm()
File "/usr/lib/obs/service/TarSCM/scm/git.py", line 91, in fetch_upstream_scm
os.removedirs(os.path.join(wdir, self.clone_dir))
File "/usr/lib64/python2.7/os.py", line 170, in removedirs
rmdir(name)
OSError: [Errno 2] No such file or directory: '/srv/obs/service/11565/out/tmpLgoRio/testpackage' 
```

If the user is omitted from the URL, then the message is "could not read Username". Those are errormessages from git.

**Comment by luc14n0** [comment]
Hi there @dsamx. This issue can get closed now, right? The #342 PR has addressed this, and nowadays OBS does even have ways to use GitHub/GitLab tokens so they can talk with each other.
