### ISSUE TITLE
v0.10.1 crash with osc service disabledrun (github repo)

### ISSUE THREAD

**Issue by tigerfoot** [openSUSE/obs-service-tar_scm#288]
Just updated  to last version of our openSUSE:Tools/openSUSE_Factory repository 

```
S  | Name                         | Type    | Version                           | Arch   | Repository
---+------------------------------+---------+-----------------------------------+--------+-----------
i+ | obs-service-appimage         | package | 0.10.1.1550758451.f88bd41-242.1   | noarch | tools
i+ | obs-service-download_files   | package | 0.6.2-83.2                        | noarch | tools
i+ | obs-service-download_url     | package | 0.1.1-21.10                       | noarch | tools
i+ | obs-service-extract_file     | package | 0.3-19.13                         | noarch | tools
i+ | obs-service-format_spec_file | package | 20180820-230.2                    | noarch | tools
i+ | obs-service-obs_scm          | package | 0.10.1.1550758451.f88bd41-242.1   | noarch | tools
i+ | obs-service-obs_scm-common   | package | 0.10.1.1550758451.f88bd41-242.1   | noarch | tools
i+ | obs-service-recompress       | package | 0.3.1+git20170704.59bf231-31.2    | noarch | tools
i+ | obs-service-refresh_patches  | package | 0.3.9+git.1537184752.d624424-24.1 | noarch | tools
i+ | obs-service-set_version      | package | 0.5.11-103.1                      | noarch | tools
i+ | obs-service-source_validator | package | 0.18-138.2                        | noarch | tools
i+ | obs-service-tar              | package | 0.10.1.1550758451.f88bd41-242.1   | noarch | tools
i+ | obs-service-verify_file      | package | 0.1.1-35.14                       | noarch | tools
```

and trying to refresh a git based package (qgis-master) I got now this error.

```
osc service disabledrun
Detected cached repository...
ddb589a3c8b35028e37aee46057465f109483366
ddb589a3c8b35028e37aee46057465f109483366
no locale set
Traceback (most recent call last):
  File "/usr/lib/obs/service/tar_scm", line 30, in <module>
    main()
  File "/usr/lib/obs/service/tar_scm", line 26, in main
    TarSCM.run()
  File "/usr/lib/obs/service/TarSCM/__init__.py", line 35, in run
    task_list.process_list()
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 118, in process_list
    self.process_single_task(task)
  File "/usr/lib/obs/service/TarSCM/tasks.py", line 205, in process_single_task
    dstname=dstname)
  File "/usr/lib/obs/service/TarSCM/scm/base.py", line 297, in prep_tree_for_archive
    shutil.copytree(src, dst, symlinks=True)
  File "/usr/lib64/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib64/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib64/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib64/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib64/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib64/python2.7/shutil.py", line 197, in copytree
    dstname = os.path.join(dst, name)
  File "/usr/lib64/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
Aborting: service call failed:  /usr/lib/obs/service/tar_scm --url git://github.com/qgis/QGIS.git --filename qgis-master --scm git --versionprefix 0~git --versionformat %cd.%h --revision master --changesgenerate enable --outdir /ioda/home/bruno/openSUSE/obs/home:bruno_friedmann:branches:Application:Geo/qgis-master/tmpDdWKEm.tar_scm.service
```

Default ENV
```
SHELL=/bin/bash
SESSION_MANAGER=local/qt-kt:@/tmp/.ICE-unix/2153,unix/qt-kt:/tmp/.ICE-unix/2153
WINDOWID=56623111
QT_SCREEN_SCALE_FACTORS=VGA-0=1;DP-0=1;DP-1=1;DP-2=1;DP-3=1;DP-4=1;DP-5=1;DP-6=1;
COLORTERM=1
SDK_HOME=/usr/lib64/jvm/java
XDG_CONFIG_DIRS=/etc/xdg
QT_SYSTEM_DIR=/usr/share/desktop-data
LESS=-M -I -R
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
HISTCONTROL=ignoreboth:erasedups
JDK_HOME=/usr/lib64/jvm/java
GTK_IM_MODULE=cedilla
MACHTYPE=x86_64-suse-linux
G_BROKEN_FILENAMES=1
HOSTNAME=qt-kt
HISTSIZE=10000
LANGUAGE=en_US:en_GB
FROM_HEADER=ioda.net
MINICOM=-c on
HISTFILESIZ=4000000
JAVA_ROOT=/usr/lib64/jvm/java
LC_ADDRESS=fr_CH.UTF-8
JAVA_HOME=/usr/lib64/jvm/java
AUDIODRIVER=pulseaudio
QT_LOGGING_RULES=*.debug=false;*.warning=false;*.error=false;org.kde.KScreen=false;kscreen.*=false;org.kde.kpasswdserver=false;org.kde.kio.kpasswdserver=false
LC_NAME=fr_CH.UTF-8
JRE_HOME=/usr/lib64/jvm/java/jre
SSH_AUTH_SOCK=/run/user/1502/ssh-agent.socket
INPUT_METHOD=
CPU=x86_64
HISTTIMEFORMAT=%F %H:%M:%S 
SHELL_SESSION_ID=b65a2d31b20742fdb012cc37668e8240
JAVA_BINDIR=/usr/lib64/jvm/java/bin
XMODIFIERS=@im=local
LIBVA_DRIVER_NAME=vdpau
DESKTOP_SESSION=/usr/share/xsessions/plasma5
LC_MONETARY=fr_CH.UTF-8
SSH_AGENT_PID=2072
GTK_RC_FILES=/etc/gtk/gtkrc:/ioda/home/bruno/.gtkrc:/ioda/home/bruno/.config/gtkrc
XCURSOR_SIZE=48
GPG_TTY=/dev/pts/1
GTK_MODULES=canberra-gtk-module
XDG_SEAT=seat0
PWD=/ioda/home/bruno/openSUSE/obs/home:bruno_friedmann:branches:Application:Geo/qgis-master
QEMU_AUDIO_DRV=pa
XDG_SESSION_DESKTOP=KDE
LOGNAME=bruno
XDG_SESSION_TYPE=x11
MANPATH=/usr/local/man:/usr/share/man
XAUTHORITY=/ioda/home/bruno/.Xauthority
LS_OPTIONS=-N --color=tty -T 0
XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/ioda/home/bruno/.gtkrc-2.0:/ioda/home/bruno/.config/gtkrc-2.0
XNLSPATH=/usr/share/X11/nls
HOME=/ioda/home/bruno
SSH_ASKPASS=/usr/lib/ssh/ssh-askpass
LC_PAPER=fr_CH.UTF-8
LANG=en_US.UTF-8
LS_COLORS=no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.dl=01;35:*.fli=01;35:*.gif=01;35:*.gl=01;35:*.jpg=01;35:*.jpeg=01;35:*.mkv=01;35:*.mng=01;35:*.mov=01;35:*.mp4=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.svg=01;35:*.tga=01;35:*.tif=01;35:*.webm=01;35:*.webp=01;35:*.wmv=01;35:*.xbm=01;35:*.xcf=01;35:*.xpm=01;35:*.aiff=00;32:*.ape=00;32:*.au=00;32:*.flac=00;32:*.m4a=00;32:*.mid=00;32:*.mp3=00;32:*.mpc=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:*.wma=00;32:*.wv=00;32:
XDG_CURRENT_DESKTOP=KDE
KONSOLE_DBUS_SERVICE=:1.36
PYTHONSTARTUP=/etc/pythonstart
KONSOLE_DBUS_SESSION=/Sessions/2
PROFILEHOME=~
OSTYPE=linux
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
QT_IM_SWITCHER=imsw-multi
LESS_ADVANCED_PREPROCESSOR=no
NNTPSERVER=news
KONSOLE_VERSION=181202
XSESSION_IS_UP=yes
KDE_SESSION_UID=1502
XDG_CACHE_HOME=/ioda/home/bruno/.cache
LESSCLOSE=lessclose.sh %s %s
XDG_SESSION_CLASS=user
TERM=xterm
LC_IDENTIFICATION=fr_CH.UTF-8
G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252
HOST=qt-kt
XAUTHLOCALHOSTNAME=qt-kt
LESSOPEN=lessopen.sh %s
USER=bruno
SDL_AUDIODRIVER=pulse
COLORFGBG=15;0
KDE_SESSION_VERSION=5
MORE=-sl
CSHEDIT=emacs
DISPLAY=:0
SHLVL=2
WINDOWMANAGER=/usr/bin/startkde
PAGER=less
LC_TELEPHONE=fr_CH.UTF-8
QT_IM_MODULE=xim
CVS_RSH=ssh
LC_MESSAGES=en_US.UTF-8
LC_MEASUREMENT=fr_CH.UTF-8
XDG_VTNR=7
XDG_SESSION_ID=1
GS_LIB=/ioda/home/bruno/.fonts
LC_CTYPE=fr_CH.UTF-8
PILOTPORT=usb:
XDG_RUNTIME_DIR=/run/user/1502
LC_TIME=fr_CH.UTF-8
QT_AUTO_SCREEN_SCALE_FACTOR=0
LC_COLLATE=fr_CH.UTF-8
XCURSOR_THEME=Breeze_Snow
XDG_DATA_DIRS=/usr/share
KDE_FULL_SESSION=true
CONFIG_SITE=/usr/share/site/x86_64-unknown-linux-gnu
PATH=/ioda/home/bruno/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/sbin:/usr/sbin
KONSOLE_PROFILE_NAME=Shell
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1502/bus
PROFILEREAD=true
MAIL=/var/spool/mail/bruno
HOSTTYPE=x86_64
LESSKEY=/etc/lesskey.bin
LC_NUMERIC=fr_CH.UTF-8
OLDPWD=/ioda/home/bruno/openSUSE/obs/home:bruno_friedmann:branches:Application:Geo
BASH_FUNC_mc%%=() {  . /usr/share/mc/mc-wrapper.sh
}
_=/usr/bin/env
```

**Comment by M0ses** [comment]
We did a lot progress on that. I hope this is fixed in v0.10.6. Could you confirm?

Sorry for inconvenience.
