### ISSUE TITLE
Service currently broken in OBS with openSUSE 15.2

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/obs-service-tar_scm#378]
This service is currently broken in the OBS for openSUSE 15.2:

```
[   59s] Unpacking routenbuch-0~git1605041142.a9c96c1.obscpio ...
[   59s] 2274 blocks
[   59s] Running build time source services...
[   59s] Traceback (most recent call last):
[   59s]   File "/usr/lib/obs/service/tar", line 22, in <module>
[   59s]     import TarSCM        # pylint: disable=wrong-import-position; # noqa: E402
[   59s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 6, in <module>
[   59s]     from TarSCM.tasks      import Tasks
[   59s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 15, in <module>
[   59s]     import yaml
[   59s] ImportError: No module named yaml
[   59s] service run failed for service 'tar'
```

https://build.opensuse.org/package/live_build_log/home:gladiac:ig-klettern/routenbuch/openSUSE_Leap_15.2/x86_64

**Comment by cryptomilk** [comment]
The package `obs-service-tar_scm` comes in via home:darix:apps which uses https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-tar_scm, so the issue comes from the devel project directly.

**Comment by olafhering** [comment]
Is this still broken?
