### ISSUE TITLE
tar service fails with changed filename param on obs_scm when running "osc service runall"

### ISSUE THREAD

**Issue by nopeinomicon** [openSUSE/obs-service-tar_scm#384]
The tar service fails to convert the obscpio archive into a tarball when running "osc service runall" with a non-default filename param on the obs_scm service. This error does not occur when building the .spec file, only when running the services independently. My _service file reads as follows:

```
<services>
  <service name="obs_scm" mode="disabled">
    <param name="versionformat">0.22.9</param>
    <param name="url">https://github.com/Bitcoin-ABC/secp256k1.git</param>
    <param name="scm">git</param>
    <param name="changesgenerate">enable</param>
    <param name="exclude">.*</param>
    <param name="filename">libsecp256k1-bitcoinabc</param>
    <param name="revision">refs/tags/v0.22.9</param>
  </service>
  <service name="tar" mode="buildtime">
  </service>
  <service name="recompress" mode="buildtime">
    <param name="compression">gz</param>
    <param name="file">*.tar</param>
  </service>
  <service name="set_version" mode="disabled">
    <param name="file">libsecp256k1-bitcoinabc.spec</param>
  </service>
  <service name="format_spec_file" mode="disabled">
    <param name="specfile">libsecp256k1-bitcoinabc.spec</param>
  </service>
</services>
```
And the command log is as follows:
```
nopeinomicon@emi-pc:~/Documents/Programming/home:nopeinomicon/libsecp256k1-bitcoinabc> osc service runall
merge: origin/refs/tags/v0.22.9 - not something we can merge
Already up to date.
533268ef2652402b3f21bd425973f54038469b26
Error while moving from 'libsecp256k1-bitcoinabc' to 'libsecp256k1-bitcoinabc-0.22.9'
Current working directory: '/home/nopeinomicon/Documents/Programming/home:nopeinomicon/libsecp256k1-bitcoinabc'
Aborting: service call failed:  /usr/lib/obs/service/tar --outdir /home/nopeinomicon/Documents/Programming/home:nopeinomicon/libsecp256k1-bitcoinabc/tmpf1zq1kpw.tar.service
```

My operating system is openSUSE Tumbleweed, all packages are up to date.

**Comment by suntorytimed** [comment]
Same issue when running a `osc service disabledrun` with this configuration:
```
<services>
  <service mode="disabled" name="obs_scm">
    <param name="url">http://svn.resourcespace.com/svn/rs/releases/9.5</param>
    <param name="scm">svn</param>
    <param name="outdir">9.5</param>
    <param name="filename">resourcespace</param>
    <param name="versionprefix">9.5</param>
    <param name="changesgenerate">disable</param>
  </service>
  <service mode="disabled" name="tar" />
  <service mode="disabled" name="recompress">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service mode="disabled" name="set_version" />
</services>
```

```
Checked out revision 17238.
Error while moving from 'resourcespace' to 'resourcespace-9.5.17237'
Current working directory: '/home/releasemanager/home:suntorytimed:branches:server:php:applications/resourcespace'
Aborting: service call failed:  /usr/lib/obs/service/tar --outdir /home/releasemanager/home:suntorytimed:branches:server:php:applications/resourcespace/tmp2g451aet.tar.service
```

**Comment by sp1ritCS** [comment]
Same issue here, a workaround I found was create a symlink named like the package that links against the folder of the SCM checkout.

**Comment by sbradnick** [comment]
> Same issue here, a workaround I found was create a symlink named like the package that links against the folder of the SCM checkout.

Thank you for making this suggestion - I was having this issue w/ a simple desire to use obs_scm to grab from https://github.com/fish-shell/fish-shell but I wanted the tarball to be "fish". Using your symlink suggestion made it all work 👍

```
<services>
  <service name="obs_scm" mode="disabled">
    <param name="url">https://github.com/fish-shell/fish-shell</param>
    <param name="scm">git</param>
    <param name="versionformat">git%cd.%h</param>
    <!-- This requires a symlink: 'ln -s fish-shell fish' -->
    <param name="filename">fish</param>
```

**Comment by mcepl** [comment]
Hmm, here I really don’t know what kind of symlink I should create:
```
mitmanek:luajit (2A1D4M) $ cat _service
<services>
  <service name="obs_scm" mode="manual">
    <param name="scm">git</param>
    <param name="url">https://github.com/LuaJIT/LuaJIT.git</param>
    <param name="versionprefix">5.1.2.1.0+git</param>
    <param name="revision">v2.1</param>
    <param name="changesgenerate">enable</param>
    <param name="changesauthor">mcepl@cepl.eu</param>
  </service>
  <service name="tar" mode="buildtime">
  </service>
  <service name="recompress" mode="buildtime">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service name="set_version" mode="manual"/>
</services>
mitmanek:luajit (1!1?1A1D4M) $ osc service ra
Running source_service 'obs_scm' ...
Cloning into '/home/matej/build/devel:languages:lua/luajit/LuaJIT'...
97813fb924edf822455f91a5fbbdfdb349e5984f
Already up to date.
97813fb924edf822455f91a5fbbdfdb349e5984f
Running source_service 'tar' ...
Error while moving from 'luajit' to 'luajit-5.1.2.1.0+git.1727870382.97813fb'
Current working directory: '/home/matej/build/devel:languages:lua/luajit'
Aborting: service call failed:  /usr/lib/obs/service/tar --outdir /home/matej/build/devel:languages:lua/luajit/tmp8q7oshsm.tar.service
mitmanek:luajit (1?2A1D4M) $ ls -1
baselibs.conf
LuaJIT
luajit.changes
luajit-lua-versioned.patch
luajit.obsinfo
LuaJIT.obsinfo
luajit.spec
luajit-s390x.patch
luajit-5.1.2.1.0+git.1727870382.97813fb.obscpio
_service
_servicedata
0002-Enable-debugging-symbols-in-the-build.patch
0003-Get-rid-of-LUAJIT_VERSION_SYM-that-changes-ABI-on-ev.patch
mitmanek:luajit (1?2A1D4M) $ 
```

**Comment by sp1ritCS** [comment]
@mcepl `ln -s LuaJIT luajit` (needs a case sensitive filesystem, but you wouldn't have this issue on a case insensitive fs 🙃)

**Comment by mcepl** [comment]
Obviously it doesn’t work on my system either:

```
mitmanek:luajit (1!1M) $ ls
baselibs.conf               _service
luajit.changes              _servicedata
luajit-lua-versioned.patch  0002-Enable-debugging-symbols-in-the-build.patch
luajit.spec                 0003-Get-rid-of-LUAJIT_VERSION_SYM-that-changes-ABI-on-ev.patch
luajit-s390x.patch
mitmanek:luajit (1!1M) $ ln -s LuaJit luajit
mitmanek:luajit (1!1?1M) $ osc service ra
Running source_service 'obs_scm' ...
Cloning into '/home/matej/build/devel:languages:lua/luajit/LuaJIT'...
97813fb924edf822455f91a5fbbdfdb349e5984f
Already up to date.
97813fb924edf822455f91a5fbbdfdb349e5984f
Running source_service 'tar' ...
Running source_service 'recompress' ...
Compressed LuaJIT-5.1.2.1.0+git.1727870382.97813fb.tar to LuaJIT-5.1.2.1.0+git.1727870382.97813fb.tar.xz
Running source_service 'set_version' ...
Traceback (most recent call last):
  File "/usr/lib/obs/service/set_version", line 457, in <module>
    files_local = _get_local_files()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/obs/service/set_version", line 56, in _get_local_files
    files.sort(key=lambda x: os.stat(os.path.join(os.getcwd(), x)).st_mtime,
  File "/usr/lib/obs/service/set_version", line 56, in <lambda>
    files.sort(key=lambda x: os.stat(os.path.join(os.getcwd(), x)).st_mtime,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/matej/build/devel:languages:lua/luajit/luajit'
Aborting: service call failed:  /usr/lib/obs/service/set_version --outdir /home/matej/build/devel:languages:lua/luajit/tmp5b8590ar.set_version.service
mitmanek:luajit (1!4?1M) $ 
```
