### ISSUE TITLE
Error in Fedora_Rawhide: AttributeError: 'RawConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

### ISSUE THREAD

**Issue by wineee** [openSUSE/obs-service-tar_scm#478]
tar service in buildtime  run failed in Fedora_Rawhide ,(Probably because of python upgrade to 3.12.0)

https://build.opensuse.org/package/show/home:rewine:vioken/qwlroots

log: https://build.opensuse.org/package/live_build_log/home:rewine:vioken/qwlroots/Fedora_Rawhide/x86_64

```
[   81s] now finalizing build dir...
[   81s] SIOCSIFADDR: File exists
[   81s] Unpacking qwlroots-0.20230725.b1d8e26.obscpio ...
[   81s] 1346 blocks
[   82s] Running build time source services...
[   82s] Traceback (most recent call last):
[   82s]   File "/usr/lib/obs/service/tar", line 30, in <module>
[   82s]     main()
[   82s]   File "/usr/lib/obs/service/tar", line 26, in main
[   82s]     TarSCM.run()
[   82s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 39, in run
[   82s]     task_list.process_list()
[   82s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 131, in process_list
[   82s]     self.process_single_task(task)
[   82s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 211, in process_single_task
[   82s]     self.scm_object = scm_object   = scm_class(args, self)
[   82s]                                      ^^^^^^^^^^^^^^^^^^^^^
[   82s]   File "/usr/lib/obs/service/TarSCM/scm/base.py", line 82, in __init__
[   82s]     self._calc_repocachedir()
[   82s]   File "/usr/lib/obs/service/TarSCM/scm/base.py", line 234, in _calc_repocachedir
[   82s]     repocachedir = Config().get('tar_scm', 'CACHEDIRECTORY')
[   82s]                    ^^^^^^^^
[   82s]   File "/usr/lib/obs/service/TarSCM/config.py", line 47, in __init__
[   82s]     self.configs.append(self._init_config(fname))
[   82s]                         ^^^^^^^^^^^^^^^^^^^^^^^^
[   82s]   File "/usr/lib/obs/service/TarSCM/config.py", line 73, in _init_config
[   82s]     config.readfp(tmp_fp)
[   82s]     ^^^^^^^^^^^^^
[   82s] AttributeError: 'RawConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
[   82s] service run failed for service 'tar'
[   82s] ### VM INTERACTION START ###
[   82s] [0;1;38;5;185mFailed to write wtmp record, ignoring: Read-only file system[0m
[   82s] [0;1;38;5;185mFailed to write utmp record: Read-only file system[0m
[   82s] Powering off.
```

**Comment by wineee** [comment]
fixed in https://github.com/openSUSE/obs-service-tar_scm/pull/475
